#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v deb-systemd-helper >/dev/null 2>&1; then
            deb-systemd-helper enable xzramd.service >/dev/null || true
            deb-systemd-helper start xzramd.service >/dev/null || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
