#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if command -v deb-systemd-helper >/dev/null 2>&1; then
            deb-systemd-helper stop xzramd.service >/dev/null || true
            deb-systemd-helper disable xzramd.service >/dev/null || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
