#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if command -v deb-systemd-invoke >/dev/null 2>&1; then
            deb-systemd-invoke stop xzramd.service >/dev/null || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
